[build-system]
requires = [
	"setuptools>=42",
	"wheel",
	"pybind11>=2.7",
	"cmake==3.29",
	"numpy>=1.4",
	"ninja",
	"scikit-build"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
